apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: anf0vhqf0-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bd42eec9e9.et7h.p3.openshiftapps.com/rhtap/rhtap-qe:df2bde2b01ff9c30526babe1bc1ca6963c90bd79@sha256:5eaa491e8c49e8c90d075ecc93c7eab0e7f18ec064b97f305c5c7147f589c062
          name: container-image
